apiVersion: v1
kind: Namespace
metadata:
  name: ams-${ENVIRONMENT}
  labels:
    app: anlagen-management-system
    environment: ${ENVIRONMENT}
    version: ${VERSION}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ams-resource-quota
  namespace: ams-${ENVIRONMENT}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ams-limit-range
  namespace: ams-${ENVIRONMENT}
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container